### ISSUE TITLE
Apple Music style

### ISSUE THREAD

**Issue by Huddie** [BasThomas/ImageAlertAction#8]
Any thoughts on an Apple music style option for this?
![GitHawk Upload by Huddie](https://i.imgur.com/oDfUxPp.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It looks really cool, but it seems like that uses quite a bit of (as of yet) private APIs.

So I'll leave it as-is for now, but would love to see Apple expanding on this API in the future :)
